name: Update Vidio streams
on:
  schedule:
    - cron: '00 00/2 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: config
        run: |
          git pull
          git config --global user.email "astvstreaming39@gmail.com"
          git config --global user.name "ASTV Streaming"
      - name: update streams
        run: |
          pwd
          mkdir tmp
          wget -U 'okhttp/1.2' -qP tmp http://103.152.118.53:80/api/pidio/index.py
          python3 tmp/index.py --channel-code 205 --channel-name "indosiar" indogsiar.m3u8
          python3 tmp/index.py --channel-code 204 --channel-name "sctv" esceteve.m3u8
          python3 tmp/index.py --channel-code 8237 --channel-name "mentari-tv" mentaritivi.m3u8
          python3 tmp/index.py --channel-code 733 --channel-name "trans-tv" transtivi.m3u8
          python3 tmp/index.py --channel-code 782 --channel-name "antv" anteve.m3u8
          python3 tmp/index.py --channel-code 206 --channel-name "moji" moujitivi.m3u8
          python3 tmp/index.py --channel-code 783 --channel-name "tvone" tiviwan.m3u8
          python3 tmp/index.py --channel-code 7464 --channel-name "ajwa-tv" ajewativi.m3u8
          python3 tmp/index.py --channel-code 734 --channel-name "trans-7" terans7.m3u8
          python3 tmp/index.py --channel-code 9714 --channel-name "jpm-tv" jepeemtivi.m3u8
          python3 tmp/index.py --channel-code 10975 --channel-name "elshinta-tv" elsehintativi.m3u8
          python3 tmp/index.py --channel-code 8241 --channel-name "rans-channel" ranschanneel.m3u8
          python3 tmp/index.py --channel-code 6362 --channel-name "tvn" tivien.m3u8
          rm -rf tmp
      - name: commit
        run: |
          git add -A
          git commit -m "Update streams"
          git push
